name: Require Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled]

jobs:
  check-labels:
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - name: Verify PR has at least one label
        uses: mheap/github-action-required-labels@8afbe8ae6ab7647d0c9f0cfa7c2f939650d22509 # v5
        with:
          mode: minimum
          count: 1
          labels: ".*"
          use_regex: true
